// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"System_Tooltips","status":true,"description":"","parameters":{}},
{"name":"System_Data","status":true,"description":"","parameters":{}},
{"name":"System_Network","status":true,"description":"","parameters":{}},
{"name":"System_Spine","status":true,"description":"","parameters":{}},
{"name":"System_LWF","status":true,"description":"","parameters":{}},
{"name":"System_BattleFlow","status":true,"description":"","parameters":{}},
{"name":"System_Character_Base","status":true,"description":"","parameters":{}},
{"name":"System_Character_State","status":true,"description":"","parameters":{}},
{"name":"System_Player_Party","status":true,"description":"","parameters":{}},
{"name":"System_Item","status":true,"description":"","parameters":{}},
{"name":"System_Voice","status":true,"description":"","parameters":{}},
{"name":"System_AI","status":true,"description":"","parameters":{}},
{"name":"UI_Base","status":true,"description":"","parameters":{}},
{"name":"UI_Button","status":true,"description":"","parameters":{}},
{"name":"UI_Spine","status":true,"description":"","parameters":{}},
{"name":"UI_Gauge","status":true,"description":"","parameters":{}},
{"name":"UI_CustomWindow","status":true,"description":"","parameters":{}},
{"name":"UI_CustomScene","status":true,"description":"","parameters":{}},
{"name":"UI_TitleScene","status":true,"description":"","parameters":{}},
{"name":"UI_UpdateScene","status":true,"description":"","parameters":{}},
{"name":"UI_MainScene","status":true,"description":"","parameters":{}},
{"name":"UI_ItemScene","status":true,"description":"","parameters":{}},
{"name":"UI_CharacterScene","status":true,"description":"","parameters":{}},
{"name":"UI_BattleScene","status":true,"description":"","parameters":{}},
{"name":"UI_BattleResult","status":true,"description":"","parameters":{}}
];
